"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useSignMessage = exports.useDisconnect = exports.useAccount = exports.useWeb3ModalEvents = exports.useWeb3Modal = exports.Web3ModalProvider = exports.loginEmail = void 0;
const index_js_1 = require("./loginMetamask/index.js");
var index_js_2 = require("./loginEmail/index.js");
Object.defineProperty(exports, "loginEmail", { enumerable: true, get: function () { return index_js_2.loginEmail; } });
var Web3ModalProvider_js_1 = require("./walletConnect/Web3ModalProvider.js");
Object.defineProperty(exports, "Web3ModalProvider", { enumerable: true, get: function () { return Web3ModalProvider_js_1.default; } });
var react_1 = require("@web3modal/wagmi/react");
Object.defineProperty(exports, "useWeb3Modal", { enumerable: true, get: function () { return react_1.useWeb3Modal; } });
Object.defineProperty(exports, "useWeb3ModalEvents", { enumerable: true, get: function () { return react_1.useWeb3ModalEvents; } });
var wagmi_1 = require("wagmi");
Object.defineProperty(exports, "useAccount", { enumerable: true, get: function () { return wagmi_1.useAccount; } });
Object.defineProperty(exports, "useDisconnect", { enumerable: true, get: function () { return wagmi_1.useDisconnect; } });
Object.defineProperty(exports, "useSignMessage", { enumerable: true, get: function () { return wagmi_1.useSignMessage; } });
console.log(index_js_1.loginMetamask);
